version: "3.8"

services:
  resume-match-app:
    image: avirooppal/resume-match-app:latest
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:8000
      - BACKEND_URL=http://localhost:8000
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: 2g
    restart: unless-stopped